### PR TITLE
Add 884 test to travis

### PR DESCRIPTION
**Pull request by willbasky**

### CODE REVIEW

**Comment by willbasky** [comment]
Not sure travis still supports the repo.

**Comment by willbasky** [comment]
btw, @epicallan I hope `1.7.0` be published soon on `Hackage` ;)

**Comment by epicallan** [comment]
> btw, @epicallan I hope 1.7.0 be published soon on Hackage ;)

@willbasky I have uploaded to hackage and I don't think Travis works it would be good to move to GitHub CI. Maybe I will get to it at some point this week.

**Comment by willbasky** [comment]
>  I have uploaded to hackage 

Thanks.

**Pull request closed without merging**
